import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "My Next App",
	description: "Generated by Nellie",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} bg-gradient-to-r from-yellow-500 via-green-500 to-pink-500 h-screen`}
			>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
